In [1]:
import pandas as pd
import matplotlib.pyplot as plt
db = pd.read_csv('season-1819.csv') # Assumes the file is in the same directory as the notebook

db.sample(10) #visualizza 10 righe a caso

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
350,11/05/19,Atalanta,Genoa,2,1,H,0,0,D,NaN,...,4,3,14,21,0,4,1,3,0,0
47,23/09/18,Milan,Atalanta,2,2,D,1,0,H,NaN,...,8,8,7,4,4,3,2,1,0,0
75,07/10/18,Lazio,Fiorentina,1,0,H,1,0,H,NaN,...,5,6,18,10,5,6,5,3,0,0
355,12/05/19,Sampdoria,Empoli,1,2,A,0,0,D,NaN,...,7,4,10,15,8,2,2,1,0,0
94,28/10/18,Milan,Sampdoria,3,2,H,2,2,D,NaN,...,7,2,11,9,5,1,3,2,0,0
212,02/02/19,Napoli,Sampdoria,3,0,H,2,0,H,NaN,...,14,2,4,12,5,3,0,3,0,0
147,09/12/18,Parma,Chievo,1,1,D,0,0,D,NaN,...,7,1,17,18,8,2,4,4,0,1
196,20/01/19,Napoli,Lazio,2,1,H,2,0,H,NaN,...,13,9,6,12,7,8,1,5,0,1
162,22/12/18,Genoa,Atalanta,3,1,H,1,0,H,NaN,...,7,6,13,13,9,6,3,2,0,2
272,16/03/19,Torino,Bologna,2,3,A,1,2,A,NaN,...,7,6,15,16,4,5,5,4,1,1

In [2]:
#crezione lista squadre uniche

squadre = pd.concat([db['HomeTeam'],db['AwayTeam']]).unique()

#creao una lista per memorizzare le statistiche delle squadre
statistiche = []

#calcolo statistiche per ciascuna squadra 

for squadra in squadre:
    partite_casa = db[db['HomeTeam']== squadra]
    partite_trasferta =db[db['AwayTeam']== squadra]

    gol_segnati_casa = partite_casa['FTHG'].sum()
    gol_segnati_ospite = partite_trasferta['FTAG'].sum()
    gol_subiti_casa = partite_casa['FTAG'].sum()
    gol_subiti_ospite = partite_trasferta['FTHG'].sum()

    totale_gol = gol_segnati_casa + gol_segnati_ospite
    totale_gol_subiti = gol_subiti_casa + gol_subiti_ospite
    totale_partite = len(partite_casa) + len(partite_trasferta)

    media_gol_segnati = totale_gol/totale_partite
    media_gol_subiti = totale_gol_subiti/totale_partite

    #calcolo vittorie , pareggie e sconfitte

    vittorie = len(partite_casa[partite_casa['FTR']=='H'])+ len(partite_trasferta[partite_trasferta['FTR']=='A'])
    pareggi = len(partite_casa[partite_casa['FTR']=='D'])+ len(partite_trasferta[partite_trasferta['FTR']=='D'])
    sconfitte = totale_partite - vittorie - pareggi

    #differenza reti

    differenza_reti = totale_gol - totale_gol_subiti

    statistiche.append({
        'squadra':squadra,
        'totale_gol':totale_gol,
        'totale_gol_subiti':totale_gol_subiti,
        'media_gol_segnati':media_gol_segnati,
        'media_gol_subiti':media_gol_subiti,
        'totale_partite':totale_partite,
        'vittorie':vittorie,
        'pareggi':pareggi,
        'sconfitte':sconfitte,
        '% vittorie':vittorie/totale_partite*100,
        '% pareggi':pareggi/totale_partite*100,
        '% sconfitte':sconfitte/totale_partite*100,
        'differenza_reti':differenza_reti
        })
    #creazione dataframe statistiche
    df_statistiche = pd.DataFrame(statistiche)
    df_statistiche.set_index('squadra',inplace = True)

In [3]:
df_statistiche.sort_values('squadra',ascending =True) #ordinamento squadre in ordine alfabetico

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti
squadra,,,,,,,,,,,,
Atalanta,77,46,2.026316,1.210526,38,20,9,9,52.631579,23.684211,23.684211,31
Bologna,48,56,1.263158,1.473684,38,11,11,16,28.947368,28.947368,42.105263,-8
Cagliari,36,54,0.947368,1.421053,38,10,11,17,26.315789,28.947368,44.736842,-18
Chievo,25,75,0.657895,1.973684,38,2,14,22,5.263158,36.842105,57.894737,-50
Empoli,51,70,1.342105,1.842105,38,10,8,20,26.315789,21.052632,52.631579,-19
Fiorentina,47,45,1.236842,1.184211,38,8,17,13,21.052632,44.736842,34.210526,2
Frosinone,29,69,0.763158,1.815789,38,5,10,23,13.157895,26.315789,60.526316,-40
Genoa,39,57,1.026316,1.500000,38,8,14,16,21.052632,36.842105,42.105263,-18
Inter,57,33,1.500000,0.868421,38,20,9,9,52.631579,23.684211,23.684211,24
Juventus,70,30,1.842105,0.789474,38,28,6,4,73.684211,15.789474,10.526316,40
Lazio,56,46,1.473684,1.210526,38,17,8,13,44.736842,21.052632,34.210526,10
Milan,55,36,1.447368,0.947368,38,19,11,8,50.000000,28.947368,21.052632,19
Napoli,74,36,1.947368,0.947368,38,24,7,7,63.157895,18.421053,18.421053,38
Parma,41,61,1.078947,1.605263,38,10,11,17,26.315789,28.947368,44.736842,-20
Roma,66,48,1.736842,1.263158,38,18,12,8,47.368421,31.578947,21.052632,18
Sampdoria,60,51,1.578947,1.342105,38,15,8,15,39.473684,21.052632,39.473684,9
Sassuolo,53,60,1.394737,1.578947,38,9,16,13,23.684211,42.105263,34.210526,-7
Spal,44,56,1.157895,1.473684,38,11,9,18,28.947368,23.684211,47.368421,-12
Torino,52,37,1.368421,0.973684,38,16,15,7,42.105263,39.473684,18.421053,15
Udinese,39,53,1.026316,1.394737,38,11,10,17,28.947368,26.315789,44.736842,-14

In [4]:
#aggiunta colonna punti totalizzati : vittoria 3 punti, pareggio 1 punto, sconfitta 0 punti
df_statistiche['punti'] = df_statistiche['vittorie']*3 + df_statistiche['pareggi']*1 + df_statistiche['sconfitte']*0
df_statistiche.sort_values('punti',ascending = False,inplace = True) #ordinamento squadre in base ai punti totalizzati
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti
squadra,,,,,,,,,,,,,
Juventus,70,30,1.842105,0.789474,38,28,6,4,73.684211,15.789474,10.526316,40,90
Napoli,74,36,1.947368,0.947368,38,24,7,7,63.157895,18.421053,18.421053,38,79
Inter,57,33,1.500000,0.868421,38,20,9,9,52.631579,23.684211,23.684211,24,69
Atalanta,77,46,2.026316,1.210526,38,20,9,9,52.631579,23.684211,23.684211,31,69
Milan,55,36,1.447368,0.947368,38,19,11,8,50.000000,28.947368,21.052632,19,68
Roma,66,48,1.736842,1.263158,38,18,12,8,47.368421,31.578947,21.052632,18,66
Torino,52,37,1.368421,0.973684,38,16,15,7,42.105263,39.473684,18.421053,15,63
Lazio,56,46,1.473684,1.210526,38,17,8,13,44.736842,21.052632,34.210526,10,59
Sampdoria,60,51,1.578947,1.342105,38,15,8,15,39.473684,21.052632,39.473684,9,53
Bologna,48,56,1.263158,1.473684,38,11,11,16,28.947368,28.947368,42.105263,-8,44
Udinese,39,53,1.026316,1.394737,38,11,10,17,28.947368,26.315789,44.736842,-14,43
Sassuolo,53,60,1.394737,1.578947,38,9,16,13,23.684211,42.105263,34.210526,-7,43
Spal,44,56,1.157895,1.473684,38,11,9,18,28.947368,23.684211,47.368421,-12,42
Cagliari,36,54,0.947368,1.421053,38,10,11,17,26.315789,28.947368,44.736842,-18,41
Fiorentina,47,45,1.236842,1.184211,38,8,17,13,21.052632,44.736842,34.210526,2,41
Parma,41,61,1.078947,1.605263,38,10,11,17,26.315789,28.947368,44.736842,-20,41
Genoa,39,57,1.026316,1.500000,38,8,14,16,21.052632,36.842105,42.105263,-18,38
Empoli,51,70,1.342105,1.842105,38,10,8,20,26.315789,21.052632,52.631579,-19,38
Frosinone,29,69,0.763158,1.815789,38,5,10,23,13.157895,26.315789,60.526316,-40,25
Chievo,25,75,0.657895,1.973684,38,2,14,22,5.263158,36.842105,57.894737,-50,20

In [5]:
#aggiungo la colonna anno al dataframe
df_statistiche['anno'] = 2019
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti,anno
squadra,,,,,,,,,,,,,,
Juventus,70,30,1.842105,0.789474,38,28,6,4,73.684211,15.789474,10.526316,40,90,2019
Napoli,74,36,1.947368,0.947368,38,24,7,7,63.157895,18.421053,18.421053,38,79,2019
Inter,57,33,1.500000,0.868421,38,20,9,9,52.631579,23.684211,23.684211,24,69,2019
Atalanta,77,46,2.026316,1.210526,38,20,9,9,52.631579,23.684211,23.684211,31,69,2019
Milan,55,36,1.447368,0.947368,38,19,11,8,50.000000,28.947368,21.052632,19,68,2019
Roma,66,48,1.736842,1.263158,38,18,12,8,47.368421,31.578947,21.052632,18,66,2019
Torino,52,37,1.368421,0.973684,38,16,15,7,42.105263,39.473684,18.421053,15,63,2019
Lazio,56,46,1.473684,1.210526,38,17,8,13,44.736842,21.052632,34.210526,10,59,2019
Sampdoria,60,51,1.578947,1.342105,38,15,8,15,39.473684,21.052632,39.473684,9,53,2019
Bologna,48,56,1.263158,1.473684,38,11,11,16,28.947368,28.947368,42.105263,-8,44,2019
Udinese,39,53,1.026316,1.394737,38,11,10,17,28.947368,26.315789,44.736842,-14,43,2019
Sassuolo,53,60,1.394737,1.578947,38,9,16,13,23.684211,42.105263,34.210526,-7,43,2019
Spal,44,56,1.157895,1.473684,38,11,9,18,28.947368,23.684211,47.368421,-12,42,2019
Cagliari,36,54,0.947368,1.421053,38,10,11,17,26.315789,28.947368,44.736842,-18,41,2019
Fiorentina,47,45,1.236842,1.184211,38,8,17,13,21.052632,44.736842,34.210526,2,41,2019
Parma,41,61,1.078947,1.605263,38,10,11,17,26.315789,28.947368,44.736842,-20,41,2019
Genoa,39,57,1.026316,1.500000,38,8,14,16,21.052632,36.842105,42.105263,-18,38,2019
Empoli,51,70,1.342105,1.842105,38,10,8,20,26.315789,21.052632,52.631579,-19,38,2019
Frosinone,29,69,0.763158,1.815789,38,5,10,23,13.157895,26.315789,60.526316,-40,25,2019
Chievo,25,75,0.657895,1.973684,38,2,14,22,5.263158,36.842105,57.894737,-50,20,2019

In [6]:
#salviamo in csv il dataframe
df_statistiche.to_csv(r'C:\Users\Alessandro\Desktop\Progetto_epicod\Partite_serieA\SerieA1819\statistiche_SerieA1819.csv')