In [1]:
import pandas as pd
import matplotlib.pyplot as plt
db = pd.read_csv('season-2021.csv') # Assumes the file is in the same directory as the notebook

db.sample(10) #visualizza 10 righe a caso

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
352,12/05/21,Bologna,Genoa,0,2,A,0,1,A,NaN,...,8,9,9,11,12,4,1,3,0,0
242,03/03/21,Cagliari,Bologna,1,0,H,1,0,H,NaN,...,5,6,15,18,10,4,2,2,0,0
134,23/12/20,Roma,Cagliari,3,2,H,1,0,H,NaN,...,9,3,18,17,6,0,3,2,0,0
88,30/11/20,Genoa,Parma,1,2,A,0,1,A,NaN,...,5,3,12,16,2,2,2,2,0,0
331,01/05/21,Milan,Benevento,2,0,H,1,0,H,NaN,...,11,2,16,8,6,7,2,0,0,0
179,22/01/21,Benevento,Torino,2,2,D,1,0,H,NaN,...,3,6,18,22,6,4,1,3,0,0
239,03/03/21,Sassuolo,Napoli,3,3,D,2,1,H,NaN,...,8,8,16,13,6,4,2,2,0,0
37,19/10/20,Verona,Genoa,0,0,D,0,0,D,NaN,...,12,2,14,15,14,2,1,4,0,0
67,08/11/20,Bologna,Napoli,0,1,A,0,1,A,NaN,...,4,4,12,11,4,7,3,0,0,0
369,18/05/21,Lazio,Torino,0,0,D,0,0,D,NaN,...,11,4,11,13,4,0,4,0,0,0

In [2]:
#crezione lista squadre uniche

squadre = pd.concat([db['HomeTeam'],db['AwayTeam']]).unique()

#creao una lista per memorizzare le statistiche delle squadre
statistiche = []

#calcolo statistiche per ciascuna squadra 

for squadra in squadre:
    partite_casa = db[db['HomeTeam']== squadra]
    partite_trasferta =db[db['AwayTeam']== squadra]

    gol_segnati_casa = partite_casa['FTHG'].sum()
    gol_segnati_ospite = partite_trasferta['FTAG'].sum()
    gol_subiti_casa = partite_casa['FTAG'].sum()
    gol_subiti_ospite = partite_trasferta['FTHG'].sum()

    totale_gol = gol_segnati_casa + gol_segnati_ospite
    totale_gol_subiti = gol_subiti_casa + gol_subiti_ospite
    totale_partite = len(partite_casa) + len(partite_trasferta)

    media_gol_segnati = totale_gol/totale_partite
    media_gol_subiti = totale_gol_subiti/totale_partite

    #calcolo vittorie , pareggie e sconfitte

    vittorie = len(partite_casa[partite_casa['FTR']=='H'])+ len(partite_trasferta[partite_trasferta['FTR']=='A'])
    pareggi = len(partite_casa[partite_casa['FTR']=='D'])+ len(partite_trasferta[partite_trasferta['FTR']=='D'])
    sconfitte = totale_partite - vittorie - pareggi

    #differenza reti

    differenza_reti = totale_gol - totale_gol_subiti

    statistiche.append({
        'squadra':squadra,
        'totale_gol':totale_gol,
        'totale_gol_subiti':totale_gol_subiti,
        'media_gol_segnati':media_gol_segnati,
        'media_gol_subiti':media_gol_subiti,
        'totale_partite':totale_partite,
        'vittorie':vittorie,
        'pareggi':pareggi,
        'sconfitte':sconfitte,
        '% vittorie':vittorie/totale_partite*100,
        '% pareggi':pareggi/totale_partite*100,
        '% sconfitte':sconfitte/totale_partite*100,
        'differenza_reti':differenza_reti
        })
    #creazione dataframe statistiche
    df_statistiche = pd.DataFrame(statistiche)
    df_statistiche.set_index('squadra',inplace = True)

In [3]:
df_statistiche.sort_values('squadra',ascending =True) #ordinamento squadre in ordine alfabetico

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti
squadra,,,,,,,,,,,,
Atalanta,90,47,2.368421,1.236842,38,23,9,6,60.526316,23.684211,15.789474,43
Benevento,40,75,1.052632,1.973684,38,7,12,19,18.421053,31.578947,50.000000,-35
Bologna,51,65,1.342105,1.710526,38,10,11,17,26.315789,28.947368,44.736842,-14
Cagliari,43,59,1.131579,1.552632,38,9,10,19,23.684211,26.315789,50.000000,-16
Crotone,45,92,1.184211,2.421053,38,6,5,27,15.789474,13.157895,71.052632,-47
Fiorentina,47,59,1.236842,1.552632,38,9,13,16,23.684211,34.210526,42.105263,-12
Genoa,47,58,1.236842,1.526316,38,10,12,16,26.315789,31.578947,42.105263,-11
Inter,89,35,2.342105,0.921053,38,28,7,3,73.684211,18.421053,7.894737,54
Juventus,77,38,2.026316,1.000000,38,23,9,6,60.526316,23.684211,15.789474,39
Lazio,61,55,1.605263,1.447368,38,21,5,12,55.263158,13.157895,31.578947,6
Milan,74,41,1.947368,1.078947,38,24,7,7,63.157895,18.421053,18.421053,33
Napoli,86,41,2.263158,1.078947,38,24,5,9,63.157895,13.157895,23.684211,45
Parma,39,83,1.026316,2.184211,38,3,11,24,7.894737,28.947368,63.157895,-44
Roma,68,55,1.789474,1.447368,38,18,9,11,47.368421,23.684211,28.947368,13
Sampdoria,52,54,1.368421,1.421053,38,15,7,16,39.473684,18.421053,42.105263,-2
Sassuolo,64,56,1.684211,1.473684,38,17,11,10,44.736842,28.947368,26.315789,8
Spezia,52,72,1.368421,1.894737,38,9,12,17,23.684211,31.578947,44.736842,-20
Torino,50,69,1.315789,1.815789,38,7,16,15,18.421053,42.105263,39.473684,-19
Udinese,42,58,1.105263,1.526316,38,10,10,18,26.315789,26.315789,47.368421,-16
Verona,43,48,1.131579,1.263158,38,10,13,15,26.315789,34.210526,39.473684,-5

In [4]:
#aggiunta colonna punti totalizzati : vittoria 3 punti, pareggio 1 punto, sconfitta 0 punti
df_statistiche['punti'] = df_statistiche['vittorie']*3 + df_statistiche['pareggi']*1 + df_statistiche['sconfitte']*0
df_statistiche.sort_values('punti',ascending = False,inplace = True) #ordinamento squadre in base ai punti totalizzati
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti
squadra,,,,,,,,,,,,,
Inter,89,35,2.342105,0.921053,38,28,7,3,73.684211,18.421053,7.894737,54,91
Milan,74,41,1.947368,1.078947,38,24,7,7,63.157895,18.421053,18.421053,33,79
Atalanta,90,47,2.368421,1.236842,38,23,9,6,60.526316,23.684211,15.789474,43,78
Juventus,77,38,2.026316,1.000000,38,23,9,6,60.526316,23.684211,15.789474,39,78
Napoli,86,41,2.263158,1.078947,38,24,5,9,63.157895,13.157895,23.684211,45,77
Lazio,61,55,1.605263,1.447368,38,21,5,12,55.263158,13.157895,31.578947,6,68
Roma,68,55,1.789474,1.447368,38,18,9,11,47.368421,23.684211,28.947368,13,63
Sassuolo,64,56,1.684211,1.473684,38,17,11,10,44.736842,28.947368,26.315789,8,62
Sampdoria,52,54,1.368421,1.421053,38,15,7,16,39.473684,18.421053,42.105263,-2,52
Verona,43,48,1.131579,1.263158,38,10,13,15,26.315789,34.210526,39.473684,-5,43
Genoa,47,58,1.236842,1.526316,38,10,12,16,26.315789,31.578947,42.105263,-11,42
Bologna,51,65,1.342105,1.710526,38,10,11,17,26.315789,28.947368,44.736842,-14,41
Udinese,42,58,1.105263,1.526316,38,10,10,18,26.315789,26.315789,47.368421,-16,40
Fiorentina,47,59,1.236842,1.552632,38,9,13,16,23.684211,34.210526,42.105263,-12,40
Spezia,52,72,1.368421,1.894737,38,9,12,17,23.684211,31.578947,44.736842,-20,39
Cagliari,43,59,1.131579,1.552632,38,9,10,19,23.684211,26.315789,50.000000,-16,37
Torino,50,69,1.315789,1.815789,38,7,16,15,18.421053,42.105263,39.473684,-19,37
Benevento,40,75,1.052632,1.973684,38,7,12,19,18.421053,31.578947,50.000000,-35,33
Crotone,45,92,1.184211,2.421053,38,6,5,27,15.789474,13.157895,71.052632,-47,23
Parma,39,83,1.026316,2.184211,38,3,11,24,7.894737,28.947368,63.157895,-44,20

In [5]:
#aggiungo la colonna anno al dataframe
df_statistiche['anno'] = 2021
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti,anno
squadra,,,,,,,,,,,,,,
Inter,89,35,2.342105,0.921053,38,28,7,3,73.684211,18.421053,7.894737,54,91,2021
Milan,74,41,1.947368,1.078947,38,24,7,7,63.157895,18.421053,18.421053,33,79,2021
Atalanta,90,47,2.368421,1.236842,38,23,9,6,60.526316,23.684211,15.789474,43,78,2021
Juventus,77,38,2.026316,1.000000,38,23,9,6,60.526316,23.684211,15.789474,39,78,2021
Napoli,86,41,2.263158,1.078947,38,24,5,9,63.157895,13.157895,23.684211,45,77,2021
Lazio,61,55,1.605263,1.447368,38,21,5,12,55.263158,13.157895,31.578947,6,68,2021
Roma,68,55,1.789474,1.447368,38,18,9,11,47.368421,23.684211,28.947368,13,63,2021
Sassuolo,64,56,1.684211,1.473684,38,17,11,10,44.736842,28.947368,26.315789,8,62,2021
Sampdoria,52,54,1.368421,1.421053,38,15,7,16,39.473684,18.421053,42.105263,-2,52,2021
Verona,43,48,1.131579,1.263158,38,10,13,15,26.315789,34.210526,39.473684,-5,43,2021
Genoa,47,58,1.236842,1.526316,38,10,12,16,26.315789,31.578947,42.105263,-11,42,2021
Bologna,51,65,1.342105,1.710526,38,10,11,17,26.315789,28.947368,44.736842,-14,41,2021
Udinese,42,58,1.105263,1.526316,38,10,10,18,26.315789,26.315789,47.368421,-16,40,2021
Fiorentina,47,59,1.236842,1.552632,38,9,13,16,23.684211,34.210526,42.105263,-12,40,2021
Spezia,52,72,1.368421,1.894737,38,9,12,17,23.684211,31.578947,44.736842,-20,39,2021
Cagliari,43,59,1.131579,1.552632,38,9,10,19,23.684211,26.315789,50.000000,-16,37,2021
Torino,50,69,1.315789,1.815789,38,7,16,15,18.421053,42.105263,39.473684,-19,37,2021
Benevento,40,75,1.052632,1.973684,38,7,12,19,18.421053,31.578947,50.000000,-35,33,2021
Crotone,45,92,1.184211,2.421053,38,6,5,27,15.789474,13.157895,71.052632,-47,23,2021
Parma,39,83,1.026316,2.184211,38,3,11,24,7.894737,28.947368,63.157895,-44,20,2021

In [6]:
#salviamo in csv il dataframe
df_statistiche.to_csv(r'C:\Users\Alessandro\Desktop\Progetto_epicod\Partite_serieA\SerieA2021\statistiche_SerieA2021.csv')