In [1]:
import pandas as pd
import matplotlib.pyplot as plt
db = pd.read_csv('season-2223.csv') # Assumes the file is in the same directory as the notebook

db.sample(10) #visualizza 10 righe a caso

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
215,12/02/23,Bologna,Monza,0,1,A,0,1,A,NaN,...,3,4,15,18,3,2,1,4,0,0
172,14/01/23,Lecce,Milan,2,2,D,2,0,H,NaN,...,3,5,11,12,8,4,1,2,0,0
131,08/11/22,Spezia,Udinese,1,1,D,1,1,D,NaN,...,6,2,12,12,9,0,3,3,0,0
208,06/02/23,Monza,Sampdoria,2,2,D,1,1,D,NaN,...,5,6,12,12,9,3,2,4,0,0
95,16/10/22,Spezia,Cremonese,2,2,D,2,1,H,NaN,...,6,4,12,11,6,8,2,0,0,0
272,01/04/23,Juventus,Verona,1,0,H,0,0,D,NaN,...,2,3,14,22,3,5,1,2,0,0
194,28/01/23,Atalanta,Sampdoria,2,0,H,1,0,H,NaN,...,5,5,17,11,7,4,0,2,0,0
164,08/01/23,Lazio,Empoli,2,2,D,1,0,H,NaN,...,4,2,17,10,10,3,4,1,0,0
378,04/06/23,Roma,Spezia,2,1,H,1,1,D,NaN,...,5,2,14,17,6,2,2,8,0,1
327,03/05/23,Verona,Inter,0,6,A,0,3,A,NaN,...,2,10,4,11,2,7,0,0,0,0

In [2]:
#crezione lista squadre uniche

squadre = pd.concat([db['HomeTeam'],db['AwayTeam']]).unique()

#creao una lista per memorizzare le statistiche delle squadre
statistiche = []

#calcolo statistiche per ciascuna squadra 

for squadra in squadre:
    partite_casa = db[db['HomeTeam']== squadra]
    partite_trasferta =db[db['AwayTeam']== squadra]

    gol_segnati_casa = partite_casa['FTHG'].sum()
    gol_segnati_ospite = partite_trasferta['FTAG'].sum()
    gol_subiti_casa = partite_casa['FTAG'].sum()
    gol_subiti_ospite = partite_trasferta['FTHG'].sum()

    totale_gol = gol_segnati_casa + gol_segnati_ospite
    totale_gol_subiti = gol_subiti_casa + gol_subiti_ospite
    totale_partite = len(partite_casa) + len(partite_trasferta)

    media_gol_segnati = totale_gol/totale_partite
    media_gol_subiti = totale_gol_subiti/totale_partite

    #calcolo vittorie , pareggie e sconfitte

    vittorie = len(partite_casa[partite_casa['FTR']=='H'])+ len(partite_trasferta[partite_trasferta['FTR']=='A'])
    pareggi = len(partite_casa[partite_casa['FTR']=='D'])+ len(partite_trasferta[partite_trasferta['FTR']=='D'])
    sconfitte = totale_partite - vittorie - pareggi

    #differenza reti

    differenza_reti = totale_gol - totale_gol_subiti

    statistiche.append({
        'squadra':squadra,
        'totale_gol':totale_gol,
        'totale_gol_subiti':totale_gol_subiti,
        'media_gol_segnati':media_gol_segnati,
        'media_gol_subiti':media_gol_subiti,
        'totale_partite':totale_partite,
        'vittorie':vittorie,
        'pareggi':pareggi,
        'sconfitte':sconfitte,
        '% vittorie':vittorie/totale_partite*100,
        '% pareggi':pareggi/totale_partite*100,
        '% sconfitte':sconfitte/totale_partite*100,
        'differenza_reti':differenza_reti
        })
    #creazione dataframe statistiche
    df_statistiche = pd.DataFrame(statistiche)
    df_statistiche.set_index('squadra',inplace = True)

In [3]:
df_statistiche.sort_values('squadra',ascending =True) #ordinamento squadre in ordine alfabetico

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti
squadra,,,,,,,,,,,,
Atalanta,66,48,1.736842,1.263158,38,19,7,12,50.000000,18.421053,31.578947,18
Bologna,53,49,1.394737,1.289474,38,14,12,12,36.842105,31.578947,31.578947,4
Cremonese,36,69,0.947368,1.815789,38,5,12,21,13.157895,31.578947,55.263158,-33
Empoli,37,49,0.973684,1.289474,38,10,13,15,26.315789,34.210526,39.473684,-12
Fiorentina,53,43,1.394737,1.131579,38,15,11,12,39.473684,28.947368,31.578947,10
Inter,71,42,1.868421,1.105263,38,23,3,12,60.526316,7.894737,31.578947,29
Juventus,56,33,1.473684,0.868421,38,22,6,10,57.894737,15.789474,26.315789,23
Lazio,60,30,1.578947,0.789474,38,22,8,8,57.894737,21.052632,21.052632,30
Lecce,33,46,0.868421,1.210526,38,8,12,18,21.052632,31.578947,47.368421,-13
Milan,64,43,1.684211,1.131579,38,20,10,8,52.631579,26.315789,21.052632,21
Monza,48,52,1.263158,1.368421,38,14,10,14,36.842105,26.315789,36.842105,-4
Napoli,77,28,2.026316,0.736842,38,28,6,4,73.684211,15.789474,10.526316,49
Roma,50,38,1.315789,1.000000,38,18,9,11,47.368421,23.684211,28.947368,12
Salernitana,48,62,1.263158,1.631579,38,9,15,14,23.684211,39.473684,36.842105,-14
Sampdoria,24,71,0.631579,1.868421,38,3,10,25,7.894737,26.315789,65.789474,-47
Sassuolo,47,61,1.236842,1.605263,38,12,9,17,31.578947,23.684211,44.736842,-14
Spezia,31,62,0.815789,1.631579,38,6,13,19,15.789474,34.210526,50.000000,-31
Torino,42,41,1.105263,1.078947,38,14,11,13,36.842105,28.947368,34.210526,1
Udinese,47,48,1.236842,1.263158,38,11,13,14,28.947368,34.210526,36.842105,-1
Verona,31,59,0.815789,1.552632,38,7,10,21,18.421053,26.315789,55.263158,-28

In [4]:
#aggiunta colonna punti totalizzati : vittoria 3 punti, pareggio 1 punto, sconfitta 0 punti
df_statistiche['punti'] = df_statistiche['vittorie']*3 + df_statistiche['pareggi']*1 + df_statistiche['sconfitte']*0
df_statistiche.sort_values('punti',ascending = False,inplace = True) #ordinamento squadre in base ai punti totalizzati
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti
squadra,,,,,,,,,,,,,
Napoli,77,28,2.026316,0.736842,38,28,6,4,73.684211,15.789474,10.526316,49,90
Lazio,60,30,1.578947,0.789474,38,22,8,8,57.894737,21.052632,21.052632,30,74
Juventus,56,33,1.473684,0.868421,38,22,6,10,57.894737,15.789474,26.315789,23,72
Inter,71,42,1.868421,1.105263,38,23,3,12,60.526316,7.894737,31.578947,29,72
Milan,64,43,1.684211,1.131579,38,20,10,8,52.631579,26.315789,21.052632,21,70
Atalanta,66,48,1.736842,1.263158,38,19,7,12,50.000000,18.421053,31.578947,18,64
Roma,50,38,1.315789,1.000000,38,18,9,11,47.368421,23.684211,28.947368,12,63
Fiorentina,53,43,1.394737,1.131579,38,15,11,12,39.473684,28.947368,31.578947,10,56
Bologna,53,49,1.394737,1.289474,38,14,12,12,36.842105,31.578947,31.578947,4,54
Torino,42,41,1.105263,1.078947,38,14,11,13,36.842105,28.947368,34.210526,1,53
Monza,48,52,1.263158,1.368421,38,14,10,14,36.842105,26.315789,36.842105,-4,52
Udinese,47,48,1.236842,1.263158,38,11,13,14,28.947368,34.210526,36.842105,-1,46
Sassuolo,47,61,1.236842,1.605263,38,12,9,17,31.578947,23.684211,44.736842,-14,45
Empoli,37,49,0.973684,1.289474,38,10,13,15,26.315789,34.210526,39.473684,-12,43
Salernitana,48,62,1.263158,1.631579,38,9,15,14,23.684211,39.473684,36.842105,-14,42
Lecce,33,46,0.868421,1.210526,38,8,12,18,21.052632,31.578947,47.368421,-13,36
Verona,31,59,0.815789,1.552632,38,7,10,21,18.421053,26.315789,55.263158,-28,31
Spezia,31,62,0.815789,1.631579,38,6,13,19,15.789474,34.210526,50.000000,-31,31
Cremonese,36,69,0.947368,1.815789,38,5,12,21,13.157895,31.578947,55.263158,-33,27
Sampdoria,24,71,0.631579,1.868421,38,3,10,25,7.894737,26.315789,65.789474,-47,19

In [5]:
#aggiungo la colonna anno al dataframe
df_statistiche['anno'] = 2023
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti,anno
squadra,,,,,,,,,,,,,,
Napoli,77,28,2.026316,0.736842,38,28,6,4,73.684211,15.789474,10.526316,49,90,2023
Lazio,60,30,1.578947,0.789474,38,22,8,8,57.894737,21.052632,21.052632,30,74,2023
Juventus,56,33,1.473684,0.868421,38,22,6,10,57.894737,15.789474,26.315789,23,72,2023
Inter,71,42,1.868421,1.105263,38,23,3,12,60.526316,7.894737,31.578947,29,72,2023
Milan,64,43,1.684211,1.131579,38,20,10,8,52.631579,26.315789,21.052632,21,70,2023
Atalanta,66,48,1.736842,1.263158,38,19,7,12,50.000000,18.421053,31.578947,18,64,2023
Roma,50,38,1.315789,1.000000,38,18,9,11,47.368421,23.684211,28.947368,12,63,2023
Fiorentina,53,43,1.394737,1.131579,38,15,11,12,39.473684,28.947368,31.578947,10,56,2023
Bologna,53,49,1.394737,1.289474,38,14,12,12,36.842105,31.578947,31.578947,4,54,2023
Torino,42,41,1.105263,1.078947,38,14,11,13,36.842105,28.947368,34.210526,1,53,2023
Monza,48,52,1.263158,1.368421,38,14,10,14,36.842105,26.315789,36.842105,-4,52,2023
Udinese,47,48,1.236842,1.263158,38,11,13,14,28.947368,34.210526,36.842105,-1,46,2023
Sassuolo,47,61,1.236842,1.605263,38,12,9,17,31.578947,23.684211,44.736842,-14,45,2023
Empoli,37,49,0.973684,1.289474,38,10,13,15,26.315789,34.210526,39.473684,-12,43,2023
Salernitana,48,62,1.263158,1.631579,38,9,15,14,23.684211,39.473684,36.842105,-14,42,2023
Lecce,33,46,0.868421,1.210526,38,8,12,18,21.052632,31.578947,47.368421,-13,36,2023
Verona,31,59,0.815789,1.552632,38,7,10,21,18.421053,26.315789,55.263158,-28,31,2023
Spezia,31,62,0.815789,1.631579,38,6,13,19,15.789474,34.210526,50.000000,-31,31,2023
Cremonese,36,69,0.947368,1.815789,38,5,12,21,13.157895,31.578947,55.263158,-33,27,2023
Sampdoria,24,71,0.631579,1.868421,38,3,10,25,7.894737,26.315789,65.789474,-47,19,2023

In [6]:
#salviamo in csv il dataframe
df_statistiche.to_csv(r'C:\Users\Alessandro\Desktop\Progetto_epicod\Partite_serieA\SerieA2223\statistiche_SerieA2223.csv')