In [1]:
import pandas as pd
import matplotlib.pyplot as plt
db = pd.read_csv('season-1516.csv') # Assumes the file is in the same directory as the notebook

db.sample(10) #visualizza 10 righe a caso

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
47,23/09/15,Palermo,Sassuolo,0,1,A,0,1,A,NaN,...,2,4,21,15,2,5,0,6,1,0
126,22/11/15,Inter,Frosinone,4,0,H,1,0,H,NaN,...,10,4,15,18,6,7,1,3,0,0
334,20/04/16,Juventus,Lazio,3,0,H,1,0,H,NaN,...,12,1,7,12,10,1,1,1,0,1
300,02/04/16,Carpi,Sassuolo,1,3,A,1,2,A,NaN,...,1,7,10,19,7,5,3,3,0,0
17,30/08/15,Roma,Juventus,2,1,H,0,0,D,NaN,...,7,2,15,16,6,6,3,2,0,2
99,29/10/15,Sampdoria,Empoli,1,1,D,0,0,D,NaN,...,3,5,19,15,6,5,2,3,0,1
329,17/04/16,Verona,Frosinone,1,2,A,0,1,A,NaN,...,4,2,23,22,4,5,3,3,0,0
373,14/05/16,Sassuolo,Inter,3,1,H,3,1,H,NaN,...,3,6,8,12,5,7,3,3,0,1
29,14/09/15,Sampdoria,Bologna,2,0,H,0,0,D,NaN,...,4,2,11,16,2,5,1,3,0,1
151,12/12/15,Palermo,Frosinone,4,1,H,2,1,H,NaN,...,6,3,18,16,6,4,2,3,0,0

In [2]:
#crezione lista squadre uniche

squadre = pd.concat([db['HomeTeam'],db['AwayTeam']]).unique()

#creao una lista per memorizzare le statistiche delle squadre
statistiche = []

#calcolo statistiche per ciascuna squadra 

for squadra in squadre:
    partite_casa = db[db['HomeTeam']== squadra]
    partite_trasferta =db[db['AwayTeam']== squadra]

    gol_segnati_casa = partite_casa['FTHG'].sum()
    gol_segnati_ospite = partite_trasferta['FTAG'].sum()
    gol_subiti_casa = partite_casa['FTAG'].sum()
    gol_subiti_ospite = partite_trasferta['FTHG'].sum()

    totale_gol = gol_segnati_casa + gol_segnati_ospite
    totale_gol_subiti = gol_subiti_casa + gol_subiti_ospite
    totale_partite = len(partite_casa) + len(partite_trasferta)

    media_gol_segnati = totale_gol/totale_partite
    media_gol_subiti = totale_gol_subiti/totale_partite

    #calcolo vittorie , pareggie e sconfitte

    vittorie = len(partite_casa[partite_casa['FTR']=='H'])+ len(partite_trasferta[partite_trasferta['FTR']=='A'])
    pareggi = len(partite_casa[partite_casa['FTR']=='D'])+ len(partite_trasferta[partite_trasferta['FTR']=='D'])
    sconfitte = totale_partite - vittorie - pareggi

    #differenza reti

    differenza_reti = totale_gol - totale_gol_subiti

    statistiche.append({
        'squadra':squadra,
        'totale_gol':totale_gol,
        'totale_gol_subiti':totale_gol_subiti,
        'media_gol_segnati':media_gol_segnati,
        'media_gol_subiti':media_gol_subiti,
        'totale_partite':totale_partite,
        'vittorie':vittorie,
        'pareggi':pareggi,
        'sconfitte':sconfitte,
        '% vittorie':vittorie/totale_partite*100,
        '% pareggi':pareggi/totale_partite*100,
        '% sconfitte':sconfitte/totale_partite*100,
        'differenza_reti':differenza_reti
        })
    #creazione dataframe statistiche
    df_statistiche = pd.DataFrame(statistiche)
    df_statistiche.set_index('squadra',inplace = True)

In [3]:
df_statistiche.sort_values('squadra',ascending =True) #ordinamento squadre in ordine alfabetico

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti
squadra,,,,,,,,,,,,
Atalanta,41,47,1.078947,1.236842,38,11,12,15,28.947368,31.578947,39.473684,-6
Bologna,33,45,0.868421,1.184211,38,11,9,18,28.947368,23.684211,47.368421,-12
Carpi,37,57,0.973684,1.500000,38,9,11,18,23.684211,28.947368,47.368421,-20
Chievo,43,45,1.131579,1.184211,38,13,11,14,34.210526,28.947368,36.842105,-2
Empoli,40,49,1.052632,1.289474,38,12,10,16,31.578947,26.315789,42.105263,-9
Fiorentina,60,42,1.578947,1.105263,38,18,10,10,47.368421,26.315789,26.315789,18
Frosinone,35,76,0.921053,2.000000,38,8,7,23,21.052632,18.421053,60.526316,-41
Genoa,45,48,1.184211,1.263158,38,13,7,18,34.210526,18.421053,47.368421,-3
Inter,50,38,1.315789,1.000000,38,20,7,11,52.631579,18.421053,28.947368,12
Juventus,75,20,1.973684,0.526316,38,29,4,5,76.315789,10.526316,13.157895,55
Lazio,52,52,1.368421,1.368421,38,15,9,14,39.473684,23.684211,36.842105,0
Milan,49,43,1.289474,1.131579,38,15,12,11,39.473684,31.578947,28.947368,6
Napoli,80,32,2.105263,0.842105,38,25,7,6,65.789474,18.421053,15.789474,48
Palermo,38,65,1.000000,1.710526,38,10,9,19,26.315789,23.684211,50.000000,-27
Roma,83,41,2.184211,1.078947,38,23,11,4,60.526316,28.947368,10.526316,42
Sampdoria,48,61,1.263158,1.605263,38,10,10,18,26.315789,26.315789,47.368421,-13
Sassuolo,49,40,1.289474,1.052632,38,16,13,9,42.105263,34.210526,23.684211,9
Torino,52,55,1.368421,1.447368,38,12,9,17,31.578947,23.684211,44.736842,-3
Udinese,35,60,0.921053,1.578947,38,10,9,19,26.315789,23.684211,50.000000,-25
Verona,34,63,0.894737,1.657895,38,5,13,20,13.157895,34.210526,52.631579,-29

In [4]:
#aggiunta colonna punti totalizzati : vittoria 3 punti, pareggio 1 punto, sconfitta 0 punti
df_statistiche['punti'] = df_statistiche['vittorie']*3 + df_statistiche['pareggi']*1 + df_statistiche['sconfitte']*0
df_statistiche.sort_values('punti',ascending = False,inplace = True) #ordinamento squadre in base ai punti totalizzati
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti
squadra,,,,,,,,,,,,,
Juventus,75,20,1.973684,0.526316,38,29,4,5,76.315789,10.526316,13.157895,55,91
Napoli,80,32,2.105263,0.842105,38,25,7,6,65.789474,18.421053,15.789474,48,82
Roma,83,41,2.184211,1.078947,38,23,11,4,60.526316,28.947368,10.526316,42,80
Inter,50,38,1.315789,1.000000,38,20,7,11,52.631579,18.421053,28.947368,12,67
Fiorentina,60,42,1.578947,1.105263,38,18,10,10,47.368421,26.315789,26.315789,18,64
Sassuolo,49,40,1.289474,1.052632,38,16,13,9,42.105263,34.210526,23.684211,9,61
Milan,49,43,1.289474,1.131579,38,15,12,11,39.473684,31.578947,28.947368,6,57
Lazio,52,52,1.368421,1.368421,38,15,9,14,39.473684,23.684211,36.842105,0,54
Chievo,43,45,1.131579,1.184211,38,13,11,14,34.210526,28.947368,36.842105,-2,50
Empoli,40,49,1.052632,1.289474,38,12,10,16,31.578947,26.315789,42.105263,-9,46
Genoa,45,48,1.184211,1.263158,38,13,7,18,34.210526,18.421053,47.368421,-3,46
Torino,52,55,1.368421,1.447368,38,12,9,17,31.578947,23.684211,44.736842,-3,45
Atalanta,41,47,1.078947,1.236842,38,11,12,15,28.947368,31.578947,39.473684,-6,45
Bologna,33,45,0.868421,1.184211,38,11,9,18,28.947368,23.684211,47.368421,-12,42
Sampdoria,48,61,1.263158,1.605263,38,10,10,18,26.315789,26.315789,47.368421,-13,40
Udinese,35,60,0.921053,1.578947,38,10,9,19,26.315789,23.684211,50.000000,-25,39
Palermo,38,65,1.000000,1.710526,38,10,9,19,26.315789,23.684211,50.000000,-27,39
Carpi,37,57,0.973684,1.500000,38,9,11,18,23.684211,28.947368,47.368421,-20,38
Frosinone,35,76,0.921053,2.000000,38,8,7,23,21.052632,18.421053,60.526316,-41,31
Verona,34,63,0.894737,1.657895,38,5,13,20,13.157895,34.210526,52.631579,-29,28

In [5]:
#aggiungo la colonna anno al dataframe
df_statistiche['anno'] = 2016
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti,anno
squadra,,,,,,,,,,,,,,
Juventus,75,20,1.973684,0.526316,38,29,4,5,76.315789,10.526316,13.157895,55,91,2016
Napoli,80,32,2.105263,0.842105,38,25,7,6,65.789474,18.421053,15.789474,48,82,2016
Roma,83,41,2.184211,1.078947,38,23,11,4,60.526316,28.947368,10.526316,42,80,2016
Inter,50,38,1.315789,1.000000,38,20,7,11,52.631579,18.421053,28.947368,12,67,2016
Fiorentina,60,42,1.578947,1.105263,38,18,10,10,47.368421,26.315789,26.315789,18,64,2016
Sassuolo,49,40,1.289474,1.052632,38,16,13,9,42.105263,34.210526,23.684211,9,61,2016
Milan,49,43,1.289474,1.131579,38,15,12,11,39.473684,31.578947,28.947368,6,57,2016
Lazio,52,52,1.368421,1.368421,38,15,9,14,39.473684,23.684211,36.842105,0,54,2016
Chievo,43,45,1.131579,1.184211,38,13,11,14,34.210526,28.947368,36.842105,-2,50,2016
Empoli,40,49,1.052632,1.289474,38,12,10,16,31.578947,26.315789,42.105263,-9,46,2016
Genoa,45,48,1.184211,1.263158,38,13,7,18,34.210526,18.421053,47.368421,-3,46,2016
Torino,52,55,1.368421,1.447368,38,12,9,17,31.578947,23.684211,44.736842,-3,45,2016
Atalanta,41,47,1.078947,1.236842,38,11,12,15,28.947368,31.578947,39.473684,-6,45,2016
Bologna,33,45,0.868421,1.184211,38,11,9,18,28.947368,23.684211,47.368421,-12,42,2016
Sampdoria,48,61,1.263158,1.605263,38,10,10,18,26.315789,26.315789,47.368421,-13,40,2016
Udinese,35,60,0.921053,1.578947,38,10,9,19,26.315789,23.684211,50.000000,-25,39,2016
Palermo,38,65,1.000000,1.710526,38,10,9,19,26.315789,23.684211,50.000000,-27,39,2016
Carpi,37,57,0.973684,1.500000,38,9,11,18,23.684211,28.947368,47.368421,-20,38,2016
Frosinone,35,76,0.921053,2.000000,38,8,7,23,21.052632,18.421053,60.526316,-41,31,2016
Verona,34,63,0.894737,1.657895,38,5,13,20,13.157895,34.210526,52.631579,-29,28,2016

In [6]:
#salviamo in csv il dataframe
df_statistiche.to_csv(r'C:\Users\Alessandro\Desktop\Progetto_epicod\Partite_serieA\SerieA1516\statistiche_SerieA1516.csv')