In [1]:
import pandas as pd
import matplotlib.pyplot as plt
db = pd.read_csv('season-1718.csv') # Assumes the file is in the same directory as the notebook

db.sample(10) #visualizza 10 righe a caso

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
63,01/10/17,Chievo,Fiorentina,2,1,H,1,1,D,NaN,...,6,4,10,10,3,7,2,1,0,0
193,06/01/18,Milan,Crotone,1,0,H,0,0,D,NaN,...,9,2,17,16,14,0,2,2,0,0
283,31/03/18,Atalanta,Udinese,2,0,H,0,0,D,NaN,...,7,2,9,10,10,6,1,2,0,0
103,29/10/17,Napoli,Sassuolo,3,1,H,2,1,H,NaN,...,9,1,14,13,6,5,2,2,0,0
336,22/04/18,Juventus,Napoli,0,1,A,0,0,D,NaN,...,0,4,10,17,3,3,3,1,0,0
345,29/04/18,Crotone,Sassuolo,4,1,H,3,1,H,NaN,...,7,6,15,8,4,6,3,1,0,0
48,20/09/17,Verona,Sampdoria,0,0,D,0,0,D,NaN,...,6,5,17,6,4,7,3,1,0,0
149,09/12/17,Juventus,Inter,0,0,D,0,0,D,NaN,...,8,1,10,21,3,4,2,5,0,0
6,20/08/17,Lazio,Spal,0,0,D,0,0,D,NaN,...,13,2,20,4,9,5,2,2,0,0
175,23/12/17,Sassuolo,Inter,1,0,H,1,0,H,NaN,...,4,4,14,18,1,10,1,2,0,0

In [2]:
#crezione lista squadre uniche

squadre = pd.concat([db['HomeTeam'],db['AwayTeam']]).unique()

#creao una lista per memorizzare le statistiche delle squadre
statistiche = []

#calcolo statistiche per ciascuna squadra 

for squadra in squadre:
    partite_casa = db[db['HomeTeam']== squadra]
    partite_trasferta =db[db['AwayTeam']== squadra]

    gol_segnati_casa = partite_casa['FTHG'].sum()
    gol_segnati_ospite = partite_trasferta['FTAG'].sum()
    gol_subiti_casa = partite_casa['FTAG'].sum()
    gol_subiti_ospite = partite_trasferta['FTHG'].sum()

    totale_gol = gol_segnati_casa + gol_segnati_ospite
    totale_gol_subiti = gol_subiti_casa + gol_subiti_ospite
    totale_partite = len(partite_casa) + len(partite_trasferta)

    media_gol_segnati = totale_gol/totale_partite
    media_gol_subiti = totale_gol_subiti/totale_partite

    #calcolo vittorie , pareggie e sconfitte

    vittorie = len(partite_casa[partite_casa['FTR']=='H'])+ len(partite_trasferta[partite_trasferta['FTR']=='A'])
    pareggi = len(partite_casa[partite_casa['FTR']=='D'])+ len(partite_trasferta[partite_trasferta['FTR']=='D'])
    sconfitte = totale_partite - vittorie - pareggi

    #differenza reti

    differenza_reti = totale_gol - totale_gol_subiti

    statistiche.append({
        'squadra':squadra,
        'totale_gol':totale_gol,
        'totale_gol_subiti':totale_gol_subiti,
        'media_gol_segnati':media_gol_segnati,
        'media_gol_subiti':media_gol_subiti,
        'totale_partite':totale_partite,
        'vittorie':vittorie,
        'pareggi':pareggi,
        'sconfitte':sconfitte,
        '% vittorie':vittorie/totale_partite*100,
        '% pareggi':pareggi/totale_partite*100,
        '% sconfitte':sconfitte/totale_partite*100,
        'differenza_reti':differenza_reti
        })
    #creazione dataframe statistiche
    df_statistiche = pd.DataFrame(statistiche)
    df_statistiche.set_index('squadra',inplace = True)

In [3]:
df_statistiche.sort_values('squadra',ascending =True) #ordinamento squadre in ordine alfabetico

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti
squadra,,,,,,,,,,,,
Atalanta,57,39,1.500000,1.026316,38,16,12,10,42.105263,31.578947,26.315789,18
Benevento,33,84,0.868421,2.210526,38,6,3,29,15.789474,7.894737,76.315789,-51
Bologna,40,52,1.052632,1.368421,38,11,6,21,28.947368,15.789474,55.263158,-12
Cagliari,33,61,0.868421,1.605263,38,11,6,21,28.947368,15.789474,55.263158,-28
Chievo,36,59,0.947368,1.552632,38,10,10,18,26.315789,26.315789,47.368421,-23
Crotone,40,66,1.052632,1.736842,38,9,8,21,23.684211,21.052632,55.263158,-26
Fiorentina,54,46,1.421053,1.210526,38,16,9,13,42.105263,23.684211,34.210526,8
Genoa,33,43,0.868421,1.131579,38,11,8,19,28.947368,21.052632,50.000000,-10
Inter,66,30,1.736842,0.789474,38,20,12,6,52.631579,31.578947,15.789474,36
Juventus,86,24,2.263158,0.631579,38,30,5,3,78.947368,13.157895,7.894737,62
Lazio,89,49,2.342105,1.289474,38,21,9,8,55.263158,23.684211,21.052632,40
Milan,56,42,1.473684,1.105263,38,18,10,10,47.368421,26.315789,26.315789,14
Napoli,77,29,2.026316,0.763158,38,28,7,3,73.684211,18.421053,7.894737,48
Roma,61,28,1.605263,0.736842,38,23,8,7,60.526316,21.052632,18.421053,33
Sampdoria,56,60,1.473684,1.578947,38,16,6,16,42.105263,15.789474,42.105263,-4
Sassuolo,29,59,0.763158,1.552632,38,11,10,17,28.947368,26.315789,44.736842,-30
Spal,39,59,1.026316,1.552632,38,8,14,16,21.052632,36.842105,42.105263,-20
Torino,54,46,1.421053,1.210526,38,13,15,10,34.210526,39.473684,26.315789,8
Udinese,48,63,1.263158,1.657895,38,12,4,22,31.578947,10.526316,57.894737,-15
Verona,30,78,0.789474,2.052632,38,7,4,27,18.421053,10.526316,71.052632,-48

In [4]:
#aggiunta colonna punti totalizzati : vittoria 3 punti, pareggio 1 punto, sconfitta 0 punti
df_statistiche['punti'] = df_statistiche['vittorie']*3 + df_statistiche['pareggi']*1 + df_statistiche['sconfitte']*0
df_statistiche.sort_values('punti',ascending = False,inplace = True) #ordinamento squadre in base ai punti totalizzati
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti
squadra,,,,,,,,,,,,,
Juventus,86,24,2.263158,0.631579,38,30,5,3,78.947368,13.157895,7.894737,62,95
Napoli,77,29,2.026316,0.763158,38,28,7,3,73.684211,18.421053,7.894737,48,91
Roma,61,28,1.605263,0.736842,38,23,8,7,60.526316,21.052632,18.421053,33,77
Inter,66,30,1.736842,0.789474,38,20,12,6,52.631579,31.578947,15.789474,36,72
Lazio,89,49,2.342105,1.289474,38,21,9,8,55.263158,23.684211,21.052632,40,72
Milan,56,42,1.473684,1.105263,38,18,10,10,47.368421,26.315789,26.315789,14,64
Atalanta,57,39,1.500000,1.026316,38,16,12,10,42.105263,31.578947,26.315789,18,60
Fiorentina,54,46,1.421053,1.210526,38,16,9,13,42.105263,23.684211,34.210526,8,57
Sampdoria,56,60,1.473684,1.578947,38,16,6,16,42.105263,15.789474,42.105263,-4,54
Torino,54,46,1.421053,1.210526,38,13,15,10,34.210526,39.473684,26.315789,8,54
Sassuolo,29,59,0.763158,1.552632,38,11,10,17,28.947368,26.315789,44.736842,-30,43
Genoa,33,43,0.868421,1.131579,38,11,8,19,28.947368,21.052632,50.000000,-10,41
Udinese,48,63,1.263158,1.657895,38,12,4,22,31.578947,10.526316,57.894737,-15,40
Chievo,36,59,0.947368,1.552632,38,10,10,18,26.315789,26.315789,47.368421,-23,40
Cagliari,33,61,0.868421,1.605263,38,11,6,21,28.947368,15.789474,55.263158,-28,39
Bologna,40,52,1.052632,1.368421,38,11,6,21,28.947368,15.789474,55.263158,-12,39
Spal,39,59,1.026316,1.552632,38,8,14,16,21.052632,36.842105,42.105263,-20,38
Crotone,40,66,1.052632,1.736842,38,9,8,21,23.684211,21.052632,55.263158,-26,35
Verona,30,78,0.789474,2.052632,38,7,4,27,18.421053,10.526316,71.052632,-48,25
Benevento,33,84,0.868421,2.210526,38,6,3,29,15.789474,7.894737,76.315789,-51,21

In [5]:
#aggiungo la colonna anno al dataframe
df_statistiche['anno'] = 2018
df_statistiche

,totale_gol,totale_gol_subiti,media_gol_segnati,media_gol_subiti,totale_partite,vittorie,pareggi,sconfitte,% vittorie,% pareggi,% sconfitte,differenza_reti,punti,anno
squadra,,,,,,,,,,,,,,
Juventus,86,24,2.263158,0.631579,38,30,5,3,78.947368,13.157895,7.894737,62,95,2018
Napoli,77,29,2.026316,0.763158,38,28,7,3,73.684211,18.421053,7.894737,48,91,2018
Roma,61,28,1.605263,0.736842,38,23,8,7,60.526316,21.052632,18.421053,33,77,2018
Inter,66,30,1.736842,0.789474,38,20,12,6,52.631579,31.578947,15.789474,36,72,2018
Lazio,89,49,2.342105,1.289474,38,21,9,8,55.263158,23.684211,21.052632,40,72,2018
Milan,56,42,1.473684,1.105263,38,18,10,10,47.368421,26.315789,26.315789,14,64,2018
Atalanta,57,39,1.500000,1.026316,38,16,12,10,42.105263,31.578947,26.315789,18,60,2018
Fiorentina,54,46,1.421053,1.210526,38,16,9,13,42.105263,23.684211,34.210526,8,57,2018
Sampdoria,56,60,1.473684,1.578947,38,16,6,16,42.105263,15.789474,42.105263,-4,54,2018
Torino,54,46,1.421053,1.210526,38,13,15,10,34.210526,39.473684,26.315789,8,54,2018
Sassuolo,29,59,0.763158,1.552632,38,11,10,17,28.947368,26.315789,44.736842,-30,43,2018
Genoa,33,43,0.868421,1.131579,38,11,8,19,28.947368,21.052632,50.000000,-10,41,2018
Udinese,48,63,1.263158,1.657895,38,12,4,22,31.578947,10.526316,57.894737,-15,40,2018
Chievo,36,59,0.947368,1.552632,38,10,10,18,26.315789,26.315789,47.368421,-23,40,2018
Cagliari,33,61,0.868421,1.605263,38,11,6,21,28.947368,15.789474,55.263158,-28,39,2018
Bologna,40,52,1.052632,1.368421,38,11,6,21,28.947368,15.789474,55.263158,-12,39,2018
Spal,39,59,1.026316,1.552632,38,8,14,16,21.052632,36.842105,42.105263,-20,38,2018
Crotone,40,66,1.052632,1.736842,38,9,8,21,23.684211,21.052632,55.263158,-26,35,2018
Verona,30,78,0.789474,2.052632,38,7,4,27,18.421053,10.526316,71.052632,-48,25,2018
Benevento,33,84,0.868421,2.210526,38,6,3,29,15.789474,7.894737,76.315789,-51,21,2018

In [6]:
#salviamo in csv il dataframe
df_statistiche.to_csv(r'C:\Users\Alessandro\Desktop\Progetto_epicod\Partite_serieA\SerieA1718\statistiche_SerieA1718.csv')